apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-card-fraud-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-card-fraud-app
  template:
    metadata:
      labels:
        app: credit-card-fraud-app
    spec:
      containers:
        - name: flask-app
          image: vikas7353/credit-card-fraud-app:latest  # Replace with your Docker image
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: credit-card-fraud-app-service
spec:
  selector:
    app: credit-card-fraud-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
